// src/components/LanguageComp.vue
<script setup>
import { Icon } from "@iconify/vue";
</script>

<template>
  <div class="text-textI text-lg leading-7 grid grid-cols-2 gap-10 mx-auto">
    <div class="flex items-center gap-x-2">
      <Icon icon="akar-icons:html-fill" class="text-[32px]" />
      <span>HTML 5</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="akar-icons:css-fill" class="text-[32px]" />
      <span>CSS 3</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="tabler:brand-javascript" class="text-[32px]" />
      <span>Javascript</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="akar-icons:typescript-fill" class="text-[32px]" />
      <span>Typescript</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="teenyicons:tailwind-solid" class="text-[32px]" />
      <span>Tailwind CSS</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="teenyicons:react-solid" class="text-[32px]" />
      <span>React JS</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="simple-icons:shadcnui" class="text-[32px]" />
      <span>Shadcn UI</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="mdi:material-ui" class="text-[32px]" />
      <span>Material UI</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="bi:filetype-scss" class="text-[32px]" />
      <span>SCSS</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="teenyicons:nextjs-outline" class="text-[32px]" />
      <span>Next JS</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="simple-icons:astro" class="text-[32px]" />
      <span>Astro</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="teenyicons:firebase-outline" class="text-[32px]" />
      <span>Firebase</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="teenyicons:vue-outline" class="text-[32px]" />
      <span>Vue 3</span>
    </div>
    <div class="flex items-center gap-x-2">
      <Icon icon="teenyicons:nodejs-outline" class="text-[32px]" />
      <span>Node JS</span>
    </div>
  </div>
</template>

// components/LanguageComp.jsx
"use client";

import { Icon } from "@iconify/react";

const languages = [
  { icon: "akar-icons:typescript-fill", name: "TypeScript" },
  { icon: "tabler:brand-javascript", name: "JavaScript (ES6+)" },
  { icon: "teenyicons:react-solid", name: "React" },
  { icon: "teenyicons:nextjs-outline", name: "Next.js 14/15" },
  { icon: "teenyicons:vue-outline", name: "Vue.js" },
  { icon: "teenyicons:nodejs-outline", name: "Node.js" },
  { icon: "akar-icons:python-fill", name: "Python" },
  { icon: "mdi:language-php", name: "PHP" },
  { icon: "simple-icons:laravel", name: "Laravel" },
  { icon: "teenyicons:tailwind-solid", name: "Tailwind CSS v4" },
  { icon: "akar-icons:html-fill", name: "HTML 5" },
  { icon: "akar-icons:css-fill", name: "CSS 3" },
  { icon: "simple-icons:astro", name: "Astro" },
  { icon: "bi:filetype-scss", name: "SCSS" },
];

export default function LanguageComp() {
  return (
    <div className="text-textI text-base md:text-lg leading-7 grid grid-cols-2 gap-6 md:gap-8 mx-auto">
      {languages.map((lang) => (
        <div key={lang.name} className="flex items-center gap-x-3 group">
          <Icon
            icon={lang.icon}
            className="text-[28px] md:text-[32px] text-accent group-hover:scale-110 transition-transform duration-200"
          />
          <span className="font-medium">{lang.name}</span>
        </div>
      ))}
    </div>
  );
}
