// components/ToolComp.jsx
"use client";

import { Icon } from "@iconify/react";

const tools = [
  { icon: "simple-icons:redux", name: "Redux Toolkit" },
  { icon: "simple-icons:reactquery", name: "TanStack Query" },
  { icon: "teenyicons:firebase-outline", name: "Firebase (Auth/DB)" },
  { icon: "simple-icons:stripe", name: "Stripe Payments" },
  { icon: "simple-icons:shadcnui", name: "Shadcn UI & Radix" },
  { icon: "simple-icons:framer", name: "Framer Motion" },
  { icon: "simple-icons:postgresql", name: "PostgreSQL" },
  { icon: "simple-icons:mongodb", name: "MongoDB" },
  { icon: "mdi:database", name: "SQL" },
  { icon: "simple-icons:zod", name: "Zod & Hook Form" },
  { icon: "simple-icons:vercel", name: "Vercel" },
  { icon: "teenyicons:git-solid", name: "Git & GitHub" },
  { icon: "teenyicons:figma-outline", name: "Figma" },
  { icon: "codicon:vscode", name: "VSCode" },
];

export default function ToolComp() {
  return (
    <div className="text-textI text-base md:text-lg leading-7 grid grid-cols-2 gap-6 md:gap-8 mx-auto">
      {tools.map((tool) => (
        <div key={tool.name} className="flex items-center gap-x-3 group">
          <Icon
            icon={tool.icon}
            className="text-[28px] md:text-[32px] text-accent group-hover:scale-110 transition-transform duration-200"
          />
          <span className="font-medium">{tool.name}</span>
        </div>
      ))}
    </div>
  );
}

// src/components/ToolComp.vue
<script setup>
import { Icon } from '@iconify/vue';
</script>

<template>
    <div class="text-textI text-lg leading-7 grid grid-cols-2 gap-10 mx-auto">
        <div class="flex items-center gap-x-2">
            <Icon icon="teenyicons:git-solid" class="text-[32px]" />
            <span>Git</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="teenyicons:github-solid" class="text-[32px]" />
            <span>Github</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="simple-icons:vercel" class="text-[32px]" />
            <span>Vercel</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="teenyicons:netlify-solid" class="text-[32px]" />
            <span>Netlify</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="codicon:vscode" class="text-[32px]" />
            <span>VSCode</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="teenyicons:figma-outline" class="text-[32px]" />
            <span>Figma</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="mdi:language-php" class="text-[32px]" />
            <span>PHP</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="simple-icons:laravel" class="text-[32px]" />
            <span>Laravel</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="simple-icons:express" class="text-[32px]" />
            <span>Express</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="simple-icons:mongodb" class="text-[32px]" />
            <span>MongoDB</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="mdi:database" class="text-[32px]" />
            <span>SQL</span>
        </div>
        <div class="flex items-center gap-x-2">
            <Icon icon="simple-icons:postgresql" class="text-[32px]" />
            <span>PostgreSQL</span>
        </div>

    </div>
</template>
